import Footer from "./components/Footer";
import "./globals.css";
import { Montserrat, Open_Sans } from "next/font/google";

const montserrat = Montserrat({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const opensans = Open_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-opensans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-montserrat font-normal ${opensans.variable}`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
